spring:
  application:
    name: todos

  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver